<?php
$this->headTitle('Login');
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <div class="form-bg">
            <div class="row">
                <div class="col-md-12">
                    <img id="photo">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->form; ?>
                    <table>
                        <tr>
                            <th>Image</th>
                        </tr>
                        <?php foreach($this->image_details as $image) { ?>
                        <tr>
                            <td><?php echo $this->escape($image->image);?></td>
                        </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
